import Head from 'next/head'
import Card from '../components/Card'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>skyGame</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch&family=Cormorant+Garamond:wght@500&family=Josefin+Sans:wght@600&family=Signika+Negative&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <Card/>
    </div>
  )
}
